apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: sample-app  # <-- Add this line
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
