apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-sample-app
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-sample-app
  template:
    metadata:
      labels:
        app: platform-sample-app
        version: v1
    spec:
      containers:
        - name: platform-sample-app
          image: nginx:latestghgh
          ports:
            - containerPort: 80
