apiVersion: v1
kind: Service
metadata:
  name: platform-app
  namespace: sample-app  # <-- Add this line
spec:
  selector:
    app: platform-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
