apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
     spec:
      containers:
        - name: hello-world
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 82

##############################################
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: sample-app
spec:
  ports:
  - port: 82
    targetPort: 82
  selector:
    app: guestbook-ui
